config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'delete_from_cart' => 'cart#delete_from_cart'

  post 'order_complete' => 'cart#order_complete'

  devise_for :users

  root 'storefront#all_products'

  get 'categorical' => 'storefront#by_category'

  get 'branding' => 'storefront#by_brand'

  resources :products
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
        can :manage, Product
    elsif user.guest?
        can :show, Product
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :product
	belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  belongs_to :user, optional: true

  serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders

  def admin?
    role == "admin"
	end

	def guest?
    role == 'guest'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :categories, :brands

  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def categories
    @categories = Category.order(:name)
  end

  def brands
    @brands = Product.pluck(:brand).sort.uniq
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :role) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :role) }
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order]
  def add_to_cart
    @order = current_order # create an order earlier using our helper method
    # get all the items from our line_item table
    line_item = @order.line_items.find_by(product_id: params[:product_id])
    # check to see if product already exists in our cart to prevent doubles
    if !line_item.blank?
      # if the item is already in the cart, update the quantity
      line_item.update(quantity: line_item.quantity += params[:quantity].to_i)
      line_item.update(line_item_total: line_item.quantity * line_item.product.price)
    else
      line_item = @order.line_items.new(product_id: params[:product_id],
                                        quantity: params[:quantity])
      @order.save
      session[:order_id] = @order.id
      line_item.update(line_item_total:
        (line_item.quantity * line_item.product.price))
    end
    redirect_back(fallback_location: root_path)
  end

  def view_order
    @line_items = current_order.line_items
  end

  def checkout
    line_items = current_order.line_items
    unless line_items.empty?
      current_order.update(user_id: current_user.id, subtotal: 0)
      @order = current_order
      line_items.each do |line_item|
        line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
        @order.order_items[line_item.product_id] = line_item.quantity 
        @order.subtotal += line_item.line_item_total
      end
      @order.save
      @order.update(sales_tax: (@order.subtotal * 0.08))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))
      session[:order_id] = nil
    end
  end

  def delete_from_cart
    line_item = LineItem.find(params[:product_id])
    line_item.update(quantity: line_item.quantity = 0)
    redirect_back(fallback_location: root_path)
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @order.line_items.destroy_all
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
  end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_products
    @products = Product.all
  end

  def by_category
    @products = Product.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end

  def by_brand
    @products = Product.where(brand: params[:brand])
    @brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Thanks for Shopping With Us!</h1>
<p>Let's review your order:</p>


<% @order.order_items.each do |key, value| %>
  <ul>
    <li><%= Product.find(key).name %></li>
    <li>Qty: <%= value %></li>
  </ul>
<% end %>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %> 
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %> 
</p>

<p>
  <strong>Order Total: </strong><%= number_to_currency @order.grand_total %> 
</p>

<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>
  Order #<%= @order.id %> will be shipping to you, 
  <%= @order.user.email %>, as soon as possible!
</p>

app/views/cart/view_order.html.erb
<% if @line_items.length > 0 %>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h2>My Cart</h2>
    </div>
    <div class="panel-body">
      <table class="table-striped">
        <thead>
          <tr>
            <th class="col-md-2">Image</th>
            <th class="col-md-2">Product</th>
            <th class="col-md-2">Unit Price</th>
            <th class="col-md-2">Quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @line_items.each do |line_item| %>
            <tr>
              <td class="col-md-2"><%= image_tag line_item.product.image.url, width:50 %></td>
              <td class="col-md-2"><%= line_item.product.name %></td>
              <td class="col-md-2"><%= number_to_currency line_item.product.price %></td>
              <td class="col-md-2"><%= line_item.quantity %></td>
              <td class="col-md-2">Subtotal: <%= number_to_currency line_item.line_item_total %></td>
              <td class="col-md-2"><%= link_to 'Put it Back', delete_from_cart_path(line_item_id: line_item.id), method: :post, class: "btn btn-danger btn-sm", data: {confirm: "You really don't want this?"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="panel-footer">
      <p><%= link_to "Finished Shopping", checkout_path, class: "btn btn-success" %> <%= link_to "Buy More Stuff", root_path, class: "btn btn-primary" %></p>
    </div>
  </div>
<% else %>
  <div>
    <h1>Cart is empty, nothing chosen for purchase!</h1>
    <%= link_to "Keep Shopping", root_path, class: "btn btn-primary"%>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
              <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @brands.each do |brand| %>
              <li><%= link_to brand, branding_path(brand: brand) %></li>
            <% end %>
              <li><%=  %></li>
          </ul>
        </li> 
        <li><%=  %></li>
        <% if user_signed_in? %>
          <li><%=  %></li>
          <li><%=  %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if LineItem.all.length > 0 %>
          <li><%= link_to "View Cart (#{LineItem.all.length})", view_order_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Hello, <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>          
          <li><%= link_to "New Account", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <%= render 'layouts/navbar' %>
    	<%= yield %>
  	</div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.select :category_id, @categories.collect {|c| [ c.name, c.id]}, {include_blank: "Please select a category" } %>
  </div>

  <div class="form-group">
    <strong>Upload Product Image: </strong>
    <%= form.file_field :image %>
  </div>


  <div class="form-group">
    <%= form.submit 'Submit', class: "btn btn-success" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-info">
  <div class="panel-heading">
    <h1>Products</h1>
  </div>
  <div class="panel-body">
    <table class="table-striped">
      <thead>
        <tr>
          <th>Category </th>
          <th>Name </th>
          <th>Brand </th>
          <th>Price </th>
          <th>Quantity </th>
          <th>Description </th>
          <th colspan="2">Actions </th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.category.name %></td>
            <td><%= link_to product.name, product %></td>
            <td><%= product.brand %></td>
            <td><%= number_to_currency product.price %></td>
            <td><%= product.quantity %></td>
            <td><%= simple_format(product.description.html_safe) %></td>
            <% if can? :update, product %>
              <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-warning btn-sm" %></td>
              <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <% if can? :create, Product %>
      <%= link_to 'New Product', new_product_path, class: "btn btn-info btn-sm" %>
    <% end %>
  </div>
</div>
<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3>Product Details</h3>
  </div>
  <div class="panel-body">
    <p><strong>Category: </strong><%= @product.category.name %></p>

    <p><strong>Brand: </strong><%= @product.brand %></p>

    <p><strong>Name: </strong><%= @product.name %></p>

    <p><strong>Price: </strong><%= number_to_currency @product.price %></p>

    <p><strong>Quantity: </strong><%= @product.quantity %></p>

    <p><strong>Description: </strong><%= simple_format(@product.description.html_safe) %></p>
  </div>
  <div class="panel-footer">
    <% if can? :update, @product %>
      <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-warning" %>
    <% end %>
      <%= link_to 'Back', products_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/storefront/_productLoop.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well text-center">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, width:300 %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href='#' data-toggle="modal" data-target="#myModal_<%= product.id %>" class="btn btn-info">
            <span class='glyphicon glyphicon-plus'></span>Buy It
          </a>
        </p>
      </div>
    </div>
    <script>
      (function () {
        var 
          elements = document.querySelectorAll(".well"),
          heights = [];

        /* Getting an array with the heights */
        [].forEach.call(elements, function(each) {
          heights[heights.length] = getComputedStyle(each, null).getPropertyValue("height");
        });

        /* Sorting the array to get the greatest value first */
        heights.sort(function(a, b) {
          return parseFloat(b) - parseFloat(a);
        });

        /* Applying the greatest height to each element */
        [].forEach.call(elements, function(each) {
          each.style.height = heights[0];
        });
      })();
    </script>

    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name%></h4>
          </div>
          <div class="modal-body">
            <% if product.image.url.nil? == false %>
		          <p><%= image_tag product.image.url, width:200 %></p>
		        <% end %>
            <p><%= number_to_currency product.price %></p>
            <p><%= simple_format(product.description.html_safe) %></p>
          </div>
          <div class="modal-footer">
            <!-- Delete those "Save Changes" and "Close" buttons that were here -->
            <p>
            <%= form_tag add_to_cart_path do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= number_field_tag :quantity, nil, min: 1, placeholder: 1 %>
              <%= submit_tag "Add to Cart", class: "btn btn-success" %>
            <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/storefront/all_products.html.erb
<h1>Welcome to Crazy Dave's Elektroniks</h1>
<p>Buy all my stuff and give me all your money!</p>
<%= render 'productLoop' %>

app/views/storefront/by_brand.html.erb
<h1>Here are our <%= @brand %> products</h1>
<%= render 'productLoop' %>

app/views/storefront/by_category.html.erb
<h1>All of our <%= @category.name %></h1>
<%= render 'productLoop' %>